version: "3"
services:
  database:
    image: postgis/postgis:15-3.4
    # Required when running on platform other than amd64, like Apple M1/M2:
    platform: linux/amd64
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
      POSTGRES_DB: "directus"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  cache:
    image: redis:7.0.7-alpine

  directus:
    image: directus-starter:latest
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
      - ./snapshots:/directus/snapshots
      - ./schema-sync:/directus/extensions/schema-sync
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_started
    #command:
    #  - /bin/sh
    #  - -c
    #  - |
    #    npx directus bootstrap &&
    #    npx directus schema apply snapshots/snapshot.yaml --yes &&
    #    npx directus start
    environment:
      EXTENSIONS_AUTO_RELOAD: "true"
      KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1"
      SECRET: "6116487b-cda1-52c2-b5b5-c8022c45e263"

      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"

      CACHE_ENABLED: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379"

      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"

  pgadmin:
    container_name: pgadmin4_directus
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    #networks:
    #  - medusa_internal
    #  - traefik
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      database:
        condition: service_healthy

volumes:
  pgadmin-data:

    # Make sure to set this in production
    # (see https://docs.directus.io/self-hosted/config-options#general)
    # PUBLIC_URL: 'https://directus.example.com'
